development:
  adapter: postgresql
  encoding: unicode
  database: db/foteq_development
  pool: 5
  username: ruben

test:
  adapter: postgresql
  encoding: unicode
  database: db/foteq_test
  pool: 5
  username: ruben

production:
  adapter: postgresql
  encoding: unicode
  database: db/foteq_production
  pool: 5
  username: ruben
